package com.example.demo.entity;

public class TestUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_USER.TESTUSERID
     *
     * @mbg.generated Fri Dec 27 21:34:21 GMT+08:00 2019
     */
    private String testuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_USER.USERNAME
     *
     * @mbg.generated Fri Dec 27 21:34:21 GMT+08:00 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_USER.PASSWORD
     *
     * @mbg.generated Fri Dec 27 21:34:21 GMT+08:00 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_USER.SEX
     *
     * @mbg.generated Fri Dec 27 21:34:21 GMT+08:00 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_USER.AGE
     *
     * @mbg.generated Fri Dec 27 21:34:21 GMT+08:00 2019
     */
    private String age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_USER.TESTUSERID
     *
     * @return the value of TEST_USER.TESTUSERID
     *
     * @mbg.generated Fri Dec 27 21:34:21 GMT+08:00 2019
     */
    public String getTestuserid() {
        return testuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_USER.TESTUSERID
     *
     * @param testuserid the value for TEST_USER.TESTUSERID
     *
     * @mbg.generated Fri Dec 27 21:34:21 GMT+08:00 2019
     */
    public void setTestuserid(String testuserid) {
        this.testuserid = testuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_USER.USERNAME
     *
     * @return the value of TEST_USER.USERNAME
     *
     * @mbg.generated Fri Dec 27 21:34:21 GMT+08:00 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_USER.USERNAME
     *
     * @param username the value for TEST_USER.USERNAME
     *
     * @mbg.generated Fri Dec 27 21:34:21 GMT+08:00 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_USER.PASSWORD
     *
     * @return the value of TEST_USER.PASSWORD
     *
     * @mbg.generated Fri Dec 27 21:34:21 GMT+08:00 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_USER.PASSWORD
     *
     * @param password the value for TEST_USER.PASSWORD
     *
     * @mbg.generated Fri Dec 27 21:34:21 GMT+08:00 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_USER.SEX
     *
     * @return the value of TEST_USER.SEX
     *
     * @mbg.generated Fri Dec 27 21:34:21 GMT+08:00 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_USER.SEX
     *
     * @param sex the value for TEST_USER.SEX
     *
     * @mbg.generated Fri Dec 27 21:34:21 GMT+08:00 2019
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_USER.AGE
     *
     * @return the value of TEST_USER.AGE
     *
     * @mbg.generated Fri Dec 27 21:34:21 GMT+08:00 2019
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_USER.AGE
     *
     * @param age the value for TEST_USER.AGE
     *
     * @mbg.generated Fri Dec 27 21:34:21 GMT+08:00 2019
     */
    public void setAge(String age) {
        this.age = age;
    }
}